TexasInstruments/processor-sdk-doc

.github/workflows/docker.yml
README.md
docker/.gitignore
docker/Dockerfile
docker/Makefile
docker/README.md
docker/root/init
requirements.txt

Use my existing container for this since it handles ID remapping automatically and has the required tools to run all the linting scripts under `bin/`.
Adds a workflow with max caching enabled to save some time.
https://github.com/StaticRocket/psdk-doc-docker
closes: #5

Docker: Add docker container under subdir with required packages

---

.github/workflows/commit-check.yml
CONTRIBUTING.md

Add a short file detailing how one can contribute to the project.
Add a commit check for PRs to make sure they are following the rules outlined in the CONTRIBUTING document.
Resolves #6 
Resolves #10

Contributing and checking commits

---

source/linux/Foundational_Components_IPC_J7200.rst
source/linux/Foundational_Components_IPC_J721E.rst
source/linux/Foundational_Components_IPC_J721S2.rst
source/linux/Foundational_Components_IPC_J722S.rst
source/linux/Foundational_Components_IPC_J742S2.rst
source/linux/Foundational_Components_IPC_J784S4.rst

Signed-off-by: Aniket Limaye <a-limaye@ti.com>

linux: Foundational_Components_IPC_J7*: Fix link to Top Level Makefile

---

configs/AM67/AM67_linux_toc.txt
configs/J722S/J722S_linux_toc.txt
source/linux/Foundational_Components/Kernel/Kernel_Drivers/E5010_JPEG_Encoder.rst

J722s and AM67 both have E5010 JPEG Encoder - need to add that doc to their respective builds.
Previous doc was also written exclusively for AM62a, so remove those hard references and make more generic.

E5010 Documentation Update

---

source/devices/AM62AX/linux/Linux_Performance_Guide.rst
source/devices/AM62PX/linux/Linux_Performance_Guide.rst
source/devices/AM62X/linux/Linux_Performance_Guide.rst

Updated DeepSleep and MCU Only LPM power measurements in the Linux performance guide.

source: devices: AM62*: linux: Updated LPM power measurements for SDK 10.0

---

configs/AM335X/AM335X_linux_toc.txt
configs/AM437X/AM437X_linux_toc.txt
configs/AM65X/AM65X_linux_toc.txt
source/devices/AM335X/linux/Release_Specific_Release_Notes.rst
source/devices/AM437X/linux/Release_Specific_Release_Notes.rst
source/devices/AM65X/linux/Release_Specific_Release_Notes.rst
source/linux/Overview/Processor_SDK_Linux_Getting_Started_Guide.rst

- Update the supported ubuntu version to 22.04
- Remove the reference of `How to Build a Ubuntu Linux host under VMware` since it is no longer maintained

Update the references of Ubuntu versions for SITARA platforms

---

conf.py

Enable the "Edit on GitHub" button. This adds a link that will automatically take users to the source of the currently viewed page on GitHub.

feat(rtd): enable the edit on github button

---

source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet_Switch.rst

Add documentation for running PTP to synchronise time between master and slave DUTs in switch mode.

feat(PRU-ICSS): Add documentation for PTP in switch mode

---

configs/AM57X/AM57X_linux_config.txt
source/linux/Overview/GCC_ToolChain.rst
source/linux/Overview/Top_Level_Makefile.rst

Updates the cross compile instructions for AM335x and AM437x to avoid the build errors while compiling the binaries for the target. 
Update the docs for packages required by host while building with Top Level Makefile

Docs Update: Update the Top Level Makefile and cross-compile instructions

---

source/common/PRU-ICSS/Getting_Started_with_PSSP.rst
source/common/PRU-ICSS/Header_Files.rst
source/common/PRU-ICSS/Overview.rst
source/common/PRU-ICSS/PRU-Cape-Building-Demos.rst
source/common/PRU-ICSS/PRU-Cape-Getting-Started-Guide.rst
source/common/PRU-ICSS/PRU-Cape-Hardware-User-Guide.rst
source/common/PRU-ICSS/PRU-Getting-Started-Labs.rst
source/common/PRU-ICSS/PRU-Hands-on-Labs.rst
source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/AM65X_PRU_ICSSG_boards.rst
source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU-ICSS_Ethernet.rst
source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet.rst
source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet_sr10.rst
source/linux/Foundational_Components/PRU-ICSS/RPMsg_Quick_Start_Guide.rst

The PRU-ICSS files have have many references of http protocol for external URLs. Fix this by switching to equivalent https URLs.
Fix the broken links as well by switching to correct URLs.

fix(PRU-ICSS): Fix broken links and switch to https

---

source/devices/J7_Family/linux/_Release_Specific_Kernel_Performance_Guide.rst

Document the unidirectional TCP throughput with different packet sizes for Ethernet over PCIe with Linux corresponding to SDK 10.01 on J7 devices.

J7_Family: Linux: Update PCIe-ETH performance for SDK 10.01

---

configs/AM335X/AM335X_linux_toc.txt
configs/AM437X/AM437X_linux_toc.txt
configs/AM57X/AM57X_linux_toc.txt
configs/AM65X/AM65X_linux_toc.txt
configs/GEN/GEN_linux_toc.txt
source/linux/Foundational_Components/Graphics/SGX/Build_Guide.rst
source/linux/Foundational_Components/Graphics/SGX/Overview.rst
source/linux/Foundational_Components_Graphics.rst

Add a simple build guide for the latest release of SGX. This goes over the various components of the SGX GFX stack, where to find them, and how to build them.

feat(graphics): add sgx latest release build guide

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/HSR_Offload.rst

Fix the script to enable / disable HSR_Offload on AM64x. The steps to enable / disable HSR_Offload mode got changed during the upstreaming of HSR driver. Fix the existing script.

fix(HSR_Offload): HSR Script

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/CPSW-EST.rst
source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/CPSW-IET.rst

Update the documentation for CPSW-EST/IET to add necessary instructions to avoid errors while updating tx channels and fix CPSW-IET documentation.

docs(linux): Network: CPSW-IET/EST: Update documentation for TSN IET/EST

---

configs/AM65X/AM65X_linux_toc.txt
source/linux/Foundational_Components_Kernel_Drivers.rst

PRUSS is only appliable for legacy devices (AM57x, AM43x, AM33x) but it is included for AM65x as well. Drop PRUSS from AM65X_linux_toc as the documentation related to PRU-ICSSG on AM65x is covered by PRU-ICSSG_Ethernet.rst file.
AM65x has CPSW2g and the AM65X_linux_toc file includes CPSW2g however CPSW2g is not added in the kernel drivers and as a result AM65x documentation doesn't show CPSW. Add CPSW2g to kernel drivers.

fix(Kernel_Drivers): Update kernel drivers for Networking

---

.github/workflows/rstcheck.yml

Disable the color output for rstcheck so the summary messages are readable in the event of a traceback.

chore(ci): disable color for rstcheck

---

configs/AM62PX/AM62PX_debian_tags.py
configs/AM62PX/AM62PX_debian_toc.txt
configs/AM62X/AM62X_debian_tags.py
configs/AM62X/AM62X_debian_toc.txt
source/debian/How_to_Guides/index_How_to_Guides.rst
source/devices/AM62PX/debian/index.rst
source/devices/AM62X/debian/index.rst
source/linux/How_to_Guides/Target/How_To_Enable_M2CC3301_in_linux.rst

Support was recently added to Debian for OOB Wifi experience using CC33xx cards. So add documentation for it.

feat: debian: Add guide to enable Wifi

---

.github/component-owners.yml
.github/workflows/component-owners.yml

Try using component-owners instead of CODEOWNERS since the latter requires all listed users have write permission to the repo.
This only requires that they were a previous contributor.
Closes #8

ci(component-owners): try using component-owners

---

.rstcheck.cfg

This warning is very rarely correct and normally doesn't mean anything. Having unused hyperlinks is one of the only way to resolve duplicate implicit target names.
Relevant issue regarding false positives:
https://github.com/rstcheck/rstcheck/issues/76

chore(rstcheck): ignore unreferenced hyperlinks

---

source/devices/J7_Family/linux/Release_Specific_Release_Notes.rst
source/devices/J7_Family/linux/Release_Specific_Yocto_layer_Configuration.rst

Update release docs for AM67, AM68, AM69
Release_notes: tag/info for meta-tisdk layer
Yocto_layer_Configuration: yocto config file for the build

feat: Update Release notes for 10.1 Jacinto Foundational SDK

---

CONTRIBUTING.md

Add a notice so contributors do not spam the doc tag unnecessarily for all changes.

docs(contributing): add note about doc tag usage

---

source/devices/AM64X/linux/RT_Linux_Performance_Guide.rst

The PCIe Controller on AM64 SoC is a Gen 2 Controller [0]. Hence, correct the speed from 8 GT/s (Gen 3) to 5 GT/s (Gen 2).
[0]: https://www.ti.com/lit/ds/symlink/am6442.pdf
Signed-off-by: Siddharth Vadapalli <s-vadapalli@ti.com>

fix: AM64X: linux: RT_Linux_Performance_Guide: correct PCIe Speed to 5 GT/s

---

source/linux/How_to_Guides/Target/How_to_enable_Microtips_LVDS_Panel.rst

Add steps for how to enable touch on Microtips panel on AM625 sk evm B/-P1 revision

fix: Add steps to enable touch on Microtips OLDI on SK-AM62B-P1

---

source/devices/AM62AX/linux/Release_Specific_Release_Notes.rst
source/devices/AM62PX/linux/Release_Specific_Release_Notes.rst
source/devices/AM62X/linux/Release_Specific_Release_Notes.rst
source/linux/Foundational_Components/Power_Management/pm_low_power_modes.rst
source/linux/Foundational_Components/Power_Management/pm_overview.rst
source/linux/Foundational_Components/Power_Management/pm_wakeup_sources.rst

Update Low power mode documentation to include the following:
1. Add details about newly added I/O Only plus DDR low power mode.
2. Update the suspend resume logs as per the latest changes.
3. Change the wakeup sources list to table to clearly describe wakeup sources supported in given low power modes.

Lpm documentation update

---

source/devices/AM62PX/linux/Release_Specific_Release_Notes.rst
source/devices/AM62X/linux/Release_Specific_Release_Notes.rst

- For SDK 10.1, update commit SHA & Release tag of meta-edegai
layer in AM62x family & AM62P which is used for ARM only Analytics [1]
- Fix indentation of important directive based on CONTRIBUTING guidelines [2]
[1]: https://git.ti.com/cgit/edgeai/meta-edgeai/tag/?h=10.01.10.04
[2]: https://github.com/TexasInstruments/processor-sdk-doc/blob/master/CONTRIBUTING.md#indentation-and-whitespace

feat(devices): Update build information for AM62x & AM62P

---

.github/workflows/build.yml
.github/workflows/deploy.yml

The workflows for working with pages artifacts are not as smart as the standard artifact routines. As such, the aggregation of previous artifacts must take place in the deploy script so the final artifact generated will have the same run-id as the deploy step that fetches it.
Fixes: 2d64c496 (feat(cicd): automated builds and deployment to pages, 2024-11-19)

ci(deploy): move aggregation step into deploy

---

source/linux/Foundational_Components/Graphics/Common/OpenGL_ES.rst
source/linux/Foundational_Components/Graphics/Common/Vulkan.rst
source/linux/Foundational_Components/Graphics/Rogue/Overview.rst
source/linux/Foundational_Components/Graphics/SGX/Overview.rst

The reg substitution is part of the isonum standard symbol definitions. The GFX sections that were already including isonum were accidentally broken when we removed the old include directives for replacevars.
Fixes: 58170050 (chore: remove all references to old include file, 2024-11-30)

fix(graphics): include isonum for reg definition

---

source/linux/How_to_Guides/FAQ/How_to_Check_Device_Tree_Info.rst

Fix the examples in this guide by implementing the following:
- Switch from xxd to hexdump since xxd is no longer packaged in fs
- Add examples and logs for am62* devices
- Update code blocks to .. code-block:: console format
- Make the document more generic by using <machine> for device in logs

fix: Update the how_to_check_device_tree_info guide

---

source/linux/Foundational_Components/Power_Management/pm_dfs.rst
source/linux/Foundational_Components/Power_Management/pm_low_power_modes.rst
source/linux/Foundational_Components/Power_Management/pm_sw_arch.rst
source/linux/Foundational_Components/Power_Management/pm_wakeup_sources.rst

Move a detailed latency constraint from device constraint section to the latency constraint section. Fix the MCU GPIO wakeup pin which was documented incorrectly. Cleanup capitalization and whitespace errors.

docs(linux): Power_Management: LPM documentation cleanups

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst

1. Add table to list down latest SDK supported sensors and daughter boards
2. Add command to apply overlay for OV2312 connected to the DS90UB954-Q1 EVM
3. Add documentation for OV5640 + Arducam V3Link (Fusion Mini) support on SK-AM62P

docs: Update CSI-RX docs for AM62, AM62P and AM62A

---

configs/AM62AX/AM62AX_linux_toc.txt
configs/AM62PX/AM62PX_linux_toc.txt
configs/AM62X/AM62X_linux_toc.txt
source/linux/Foundational_Components/System_Security/SELinux.rst
source/linux/Foundational_Components_Security.rst

This document details how to build and use SELinux on Yocto and Debian distributions.
In order to prepare for the upcoming system security documentation, this guide has been separated into another directory: System_Security.

docs(linux): Security: Add SELinux documentation

---

README.md

- GitHub Pages are now live for all DEVFAMILY and OS supported by this repository.
- Hence, update the README to highlight the same.

docs(README): Add a section for Github Pages

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/E5010_JPEG_Encoder.rst
source/linux/Foundational_Components/U-Boot/UG-Splash-Screen.rst
source/linux/Foundational_Components_IPC62px.rst
source/linux/Foundational_Components_IPC62x.rst

- Bump up the URLs under Foundational Components to 10.01.10
- Indent content under note directive as per guidelines [1]
[1]: https://github.com/TexasInstruments/processor-sdk-doc/blob/master/CONTRIBUTING.md#indentation-and-whitespace

feat(linux): Foundational components: Bump up to 10.01.10

---

source/debian/Building_Debian_Image.rst
source/debian/Building_Debian_Packages.rst

We have a tree structure in the docs, which gives an overview of the ti-bdebstrap repository. We also have example bash commands for checking out release tags of each release, for ti-bdebstrap.
In all these cases, update the version from 10.00.07 to 10.01.10.04.

feat: debian: Update version in docs

---

docker/Dockerfile

Alpine's default diff provider is Busybox diff. This is not adequate for our scripts like delta.sh or check-warn.sh. These require proper gnu-diff for advanced parameters like changed-group-format.
Fixes: 23fbd1ae (feat(docker): use alpine for the base image, 2024-11-09)

fix: add proper diffutils to container

---

configs/AM62X/AM62X_linux_toc.txt
source/linux/How_to_Guides/Host/Minimal_Platform_Development.rst
source/linux/How_to_Guides_Developer_Notes.rst

This reverts commit ef600ddd3fb335f745ac179f15eb0526ea2a6418.
https://www.ti.com/lit/pdf/spradd1 is now published.
Enable back the minimal platform board porting guide for AM62x.

AM62x: Add minimal platform board port guide

---

source/android/Foundational_Components_Bootloaders.rst

Right now, we point to the bootloaders.xml file, which is the latest (developement) manifest.
To be consistent with kernel build, pass the release manifest instead to the repo init command.
@vishalmti @glaroque

fix(android): bootloaders: Fix repo init to use release manifest

---

source/devices/AM62PX/android/Release_Specific_Release_Notes.rst
source/devices/AM62X/android/Release_Specific_Release_Notes.rst

* Remove jack playback
* List U-Boot environment issue
@vishalmti @glaroque

Android: Update known issues for SDK 10.1

---

source/devices/AM62PX/linux/Release_Specific_Release_Notes.rst
source/devices/AM62X/linux/Release_Specific_Release_Notes.rst
source/devices/AM64X/linux/Release_Specific_Release_Notes.rst

Add resolved issues to released notes of AM62PX, AM62X and AM64X.

feat: devices: Add EXT_SITMPUSW resolved issues to release notes

---

source/linux/Foundational_Components/Tools/Flash_via_Fastboot.rst

Snagfactory flashing will fail if fastboot buffer size is smaller than the file being flashed for non-sparse images. Add a note for the same.

feat(Snagfactory): Add a note for Fastboot buffer size

---

source/common/PRU-ICSS/PRU-Getting-Started-Labs.rst
source/devices/AM62AX/index_RTOS.rst
source/devices/AM62AX/linux/Overview/Build_and_Run_the_Demos.rst
source/devices/AM62PX/index_RTOS.rst
source/devices/AM62PX/linux/Overview/Build_and_Run_the_Demos.rst
source/devices/AM62PX/linux/Overview/Download_and_Install_the_SDK.rst
source/devices/AM62X/index_RTOS.rst
source/devices/AM62X/linux/Overview/Build_and_Run_the_Demos.rst
source/devices/AM62X/linux/Overview/Download_and_Install_the_SDK.rst
source/devices/AM64X/index_RTOS.rst
source/devices/AM64X/linux/Overview/Build_and_Run_the_Demos.rst
source/linux/Foundational_Components_IPC64x.rst
source/linux/How_to_Guides/Target/How_to_boot_quickly.rst
source/system/Demo_User_Guides/Benchmark_Demo_User_Guide.rst
source/system/Demo_User_Guides/Display_Cluster_User_Guide.rst

To make MCU+ SDK links work with 10.1 docs:
* update AM64X links to 10_01_00_32
* update AM62X, AM62AX, AM62PX links to 10_01_00_33

feat: Update mcu-plus-sdk versions in hyperlinks

---

configs/AM335X/AM335X_linux_toc.txt
configs/AM437X/AM437X_linux_toc.txt
source/linux/Overview/_Processor_SDK_Linux_Software_Developers_Guide.rst

Currently there was no support on these protocols, so remove from the docs index page until further clarity.

fix(PRU-ICSS): Remove the PRU-ICSS table that comes up on Sitara Legacy devices docs index page for now

---

source/devices/AM62PX/linux/Release_Specific_Release_Notes.rst
source/devices/AM62X/linux/Release_Specific_Release_Notes.rst

Since Debian now supports wifi, add it in Release Notes under the "What's New" section.

feat: debian: Add Debian's new features in Release Notes

---

source/android/Foundational_Components_Kernel.rst
source/devices/AM62PX/android/Application_Notes.rst
source/devices/AM62X/android/Application_Notes.rst

For Android newcomers, it's not trivial to know how to add new device tree
overlays. See [1]
Since it's different than the linux SDK, we should document it.
Add a section in the kernel guide for this.
[1] https://e2e.ti.com/support/processors-group/processors/f/processors-forum/1454200/sk-am62p-lp-sk-am62p-lp-androidautomotive-unable-to-get-the-dsi-port-up-and-running
While at it, also:
- Fix a build warning about a missing file in the TOC
- Reindent an implicit numbered list in the kernel guide
Cc: @vishalmti @glaroque

Android: Document how to add new overlays in the dtbo.img

---

source/linux/Foundational_Components/Graphics/Common/Weston.rst

Add a note about Weston backends, what is selected by default, and how those affect the start of Weston.

feat(weston): add note about weston backends

---

source/linux/Foundational_Components/Kernel/_Users_Guide.rst
source/linux/Overview/GCC_ToolChain.rst
source/linux/Overview/_Processor_SDK_Linux_Directory_Structure.rst

Fix the invalid architectural references and update cross-compile instructions.
For final docs page view checkout: https://jeevantelukula.github.io/processor-sdk-doc-fork/processor-sdk-linux-AM335X/esd/docs/09_03_05_02/linux/Overview/GCC_ToolChain.html

fix: Update GCC_Toolchain instructions for AM335x/AM437x/AM57x

---

source/linux/Foundational_Components/Graphics/Common/QT_Graphics_Framework.rst

Add a disclaimer about the EGLFS backend and the required device parameter, since it's a little unclear what could cause "Failed to create display device" error messages.

fix: add disclaimer about qt eglfs backend

---

source/common/PRU-ICSS/Overview.rst

The doc currently references a broken link to XDS_Performance_comparison file which doesn't exist anymore. Modify the doc to drop the reference to this.

fix(PRU-ICSS): Broken link to XDS Performance Comparison

---

source/linux/Foundational_Components/U-Boot/UG-Splash-Screen.rst

Adding 'CONFIG_VIDEO_LOGO' for splashscreen at u-boot proper.

docs(linux): Update U-Boot Splash Screen docs for AM62 family

---

source/android/Foundational_Components_Bootloaders.rst
source/android/Foundational_Components_Kernel.rst
source/android/Overview_Building_the_SDK.rst

See each individual commit for details.

Android: improve kernel guide + remove un-needed CONFIG_part_variant conditionals

---

configs/AM62AX/AM62AX_linux_toc.txt
configs/AM62PX/AM62PX_linux_toc.txt
configs/AM62X/AM62X_linux_toc.txt
configs/AM64X/AM64X_linux_toc.txt
configs/J7200/J7200_linux_toc.txt
configs/J721E/J721E_linux_toc.txt
configs/J721S2/J721S2_linux_toc.txt
configs/J722S/J722S_linux_toc.txt
configs/J742S2/J742S2_linux_toc.txt
configs/J784S4/J784S4_linux_toc.txt
source/linux/Foundational_Components/Kernel/Kernel_Drivers/DM-Timer.rst
source/linux/Foundational_Components/Kernel/Kernel_Drivers/PWM.rst
source/linux/Foundational_Components_Kernel_Drivers.rst

This patch adds initial documentation for DM-Timer found on K3 SoCs.

feat: Linux: drivers: Add initial DM-Timer documentation

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/HSR_Offload.rst
source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet.rst

Add documentation for multicast filtering for VLAN interfaces in dual EMAC and HSR offload mode for ICSSG driver.

feat(PRU-ICSS): Add Multicast+VLAN filtering documentation

---

source/linux/Overview/Top_Level_Makefile.rst

Add libgnutls28-dev package to be installed before running makefile targets

fix(linux makefile): Update packages for building the makefile targets

---

.github/workflows/build.yml

Now that base platform support has been added, enable CICD builds for AM62LX for the linux and buildroot OS configs.

feat: enable cicd builds for AM62LX

---

.github/workflows/build.yml

Buildroot flavor of AM62LX docs are not ready yet. Disabling it from CICD flow for now.

feat: temp: Disable Buildroot cicd builds for AM62LX

---

source/linux/Foundational_Components/U-Boot/UG-General-Info.rst

libgnutls28-dev provides gnutls/gnutls.h header which is required to build u-boot. Without this package, the u-boot build fails.

fix: U-Boot General Info: Update host dependency list

---

source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet.rst

Current documentation doesn't explicitly talk about single and dual EMAC support for a given MII configuration and its limitations. Add these details to avoid confusion in terms of MII configuration.

fix(PRU-ICSS): Fix MII support documentation

---

source/linux/How_to_Guides/Target/How_To_Enable_M2CC3301_in_linux.rst

Add the overlay description to enable M2-CC3351 on AM62L-EVM. Because the DTBO name has changed, also update the dtbo name for the other targets.

feat: Linux: Enable M2-CC3351 on AM62L-EVM

---

source/devices/AM62LX/linux/Release_Specific_Release_Notes.rst

Add LVGL OOB demo, Jailhouse with kernel 6.12 and Multi-distro support in the "What's New" section of the release notes. Further specify versions of Debian and Buildroot being used for the release.
cc: @paresh-bhagat12 please check Jailhouse and Buildroot notes

docs: linux: AM62LX: Update release notes with SDK highlights

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/CPSW-Ethernet.rst
source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/CPSW3g.rst
source/linux/Foundational_Components/U-Boot/UG-DFU.rst

Add documentation for CPSW3G in Linux and for USB DFU boot and DFU flash support in U-Boot on AM62LX.

AM62LX CPSW and USB doc update

---

source/linux/Foundational_Components_ATF.rst

TF-A no longer has any K3_PM_SYSTEM_SUSPEND option, hence this step is no longer relevant.
Also add AM62L relevant docs here.
---
**TI Internal Preview:** http://lcpd911.dhcp.ti.com/sharing/am62l/docs/linux/Foundational_Components_ATF.html

TF-A: Update TF-A docs for 11.00 release and AM62L APL

---

configs/AM62LX/AM62LX_linux_toc.txt

The current documentation for Power Management does not apply to the AM62LX. The information included is either incorrect or untested on. Therefore, remove the Power Management documentation from AM62LX documentation.

feat(linux): AM62LX: Remove Power Management docs from toc

---

source/devices/AM62LX/linux/Linux_Performance_Guide.rst

Update the Linux performance guide for 11.00 release for am62Lx device.
This patch currently does not include MMC/CRYPTO/USB performance numbers, these will be added in a subsequent patch.

perf(linux): Update Linux performance guide for am62lx 11.00 release

---

.github/component-owners.yml

There appears to be a case sensitive match in the group logic from component-owners that is potentially incorrectly labeling groups as users and passing it along to the GitHub API triggering some cryptic errors about being unable to "resolve a node with the global id of \<hash>".
Set groups to lowercase since that's primarily what GitHub uses behind the scenes anyway.

fix(component-owners): use lowercase team names

---

source/linux/Foundational_Components/Graphics/Common/QT_Graphics_Framework.rst

Qt6 seems to addresses the issue of incorrectly picking a card device in a multi-device environment. Drop that warning. Update example commands for new paths and replace Qt5 references with Qt6.

feat(qt): bump examples and docs for qt6

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Storage/MMC-SD.rst
source/linux/Foundational_Components/U-Boot/UG-Memory-K3.rst

This  PR documents MMCSD boot from eMMC UDA in FS mode. This is necessary since we only document eMMC boot but this boot mode may not always be supported and is not supported for am62l, see details in errata: https://www.ti.com/lit/pdf/sprz582.

Add MMCSD boot from eMMC UDA in FS mode

---

source/linux/Foundational_Components/U-Boot/UG-General-Info.rst

Quite a lot has changed for the AM62Lx boot flow when compared to more traditional AM62 devices. After hiding un-necessary sections document via ASCII charts the bootflow between the SMS and A53 cores along with the memory layout of the 2 SRAM spaces during the boot sequence
Unfortunately this will create a lot of warnings about undefined references to optee. Other than creating an entirely new U-Boot file for 62L I don't think we can get rid of them now. One idea is to add optee back in with a simple landing page saying something along the lines of `raise NotImplementedError()` or something

U-Boot: refactor general info for the AM62Lx boot flow

---

source/linux/Foundational_Components/Graphics/Common/Weston.rst
source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst

Inform the user about the new display manager and how that interacts with the Weston session. Update other sections accordingly.

feat: add info about new display manager emptty

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Storage/MMC-SD.rst
source/linux/Foundational_Components/U-Boot/UG-Memory-K3.rst

Document errata i2458 for eMMC HS400 bus mode. If support for eMMC HS400 is still required, provide instructions for enabling eMMC HS400 mode.

feat(linux): document errata i2458 for eMMC HS400

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst

Add documentation on using FPDLink IV based fusion 2 EVM with J784S4 and J742S2 EVM.

docs: kernel: CSI2RX: Add information on Fusion 2 EVM

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/E5010_JPEG_Encoder.rst

Cropping support has been added to the v4l2jpegenc element allowing for custom crop rectangles to be set. This feature is specific to TI's AM62a SDK offering as this feature is not in upstream version of Gstreamer. As a result, information and examples are needed in documentation to provide proper usage of the property.

fix: Kernel: E5010: Add Information on Cropping

---

source/android/Foundational_Components_Bootloaders.rst
source/android/Foundational_Components_Kernel.rst
source/android/Overview_Building_the_SDK.rst

Update manifests names for TI SDK, Kernel and Bootloader.
Update the commands given to fetch the code with the new manifests names for 
the TI SDK, Kernel and Bootloader.
cc @vishalmti @glaroque

feat(android): AM62X/AM62PX: update manifests to version 10.01.01

---

source/devices/AM62AX/linux/Linux_Performance_Guide.rst
source/devices/AM62AX/linux/RT_Linux_Performance_Guide.rst
source/devices/AM62PX/linux/Linux_Performance_Guide.rst
source/devices/AM64X/linux/RT_Linux_Performance_Guide.rst

This PR is a follow-up update for performance data on the following:
am62px:
- update UBOOT MMCSD FAT
am64x:
- update ARM bench STREAM
- remove Crypto IPSEC
- remove PCIE
am62ax:
- update Linux performance numbers for all sections except lowpower & cyclic tests

11.0 Performance updates

---

source/linux/Foundational_Components/U-Boot/UG-Splash-Screen.rst

Add a sub-section for disabling splash in U-boot splashscreen docs.

fix: linux: Add a sub-section for disabling splash

---

source/devices/AM62AX/linux/Release_Specific_Release_Notes.rst
source/devices/AM62PX/linux/Release_Specific_Release_Notes.rst
source/devices/AM62X/linux/Release_Specific_Release_Notes.rst
source/devices/AM64X/linux/Release_Specific_Release_Notes.rst

Add link for TIFS/SYSFW release notes for version used in SDK 11.0.

docs(linux): AM64X/AM62X/AM62AX/AM62PX: Add SYSFW release note info

---

configs/AM64X/AM64X_linux_toc.txt

When the documentation for tuning the SoC for the real-time linux kernel was added the AM64x family was missed. Add the 'How to Tune Real Time Linux' to the build list for the AM64x family.

fix(linux): add Real-Time Linux Tuning to the AM64x build

---

source/linux/Foundational_Components/Power_Management/pm_low_power_modes.rst
source/linux/Foundational_Components/Power_Management/pm_sw_arch.rst
source/linux/Foundational_Components/Power_Management/pm_wakeup_sources.rst

Updates include:
- Update how to enable CAN UART wakeup for every LPM. Remove references to enabling via ethtools or setting the register manually
- Update the units used for CPU resume latency. They were previously ms and are now us
- Change any URL that references SDK 10.1 to 11.00.09

Documentation updates for LPM

---

source/devices/AM62PX/linux/Linux_Performance_Guide.rst
source/devices/AM62X/linux/Linux_Performance_Guide.rst

Manually the GLMark2 scores in this section for AM62X/AM62PX while we're working on fixing the automation.

feat(perf): update am62/am62p glmark2 scores for 11.0

---

source/devices/AM62X/linux/Release_Specific_Release_Notes.rst

PRU RPMsg enablement on top of 11.0 release needs additional information. This is documented in detail under e2e FAQ.
This fix is to refer the FAQ info in release summary section.

docs(linux): AM62X: Add Info on PRU RPMsg for 11.0

---

source/devices/AM62PX/linux/Release_Specific_Release_Notes.rst
source/devices/AM62X/linux/Release_Specific_Release_Notes.rst

In 11.0, the OOB TI Apps Launcher uses Qt6 Framework. In earlier releases, it used Qt5. Highlight this change in release notes for 11.0.

docs(linux): AM62PX, AM62X: Release Notes: Add ti-apps-launcher with Qt6

---

source/linux/Foundational_Components/Kernel/_Users_Guide.rst

The SK platforms now all have a separate defconfig so the following should not be required anymore.

fix(linux): Remove the additional instructions for SK platforms

---

source/linux/Foundational_Components/Power_Management/pm_low_power_modes.rst
source/linux/Foundational_Components/Power_Management/pm_sw_arch.rst
source/linux/Foundational_Components/Power_Management/pm_wakeup_sources.rst

Documentation updates to address comments from Akash's comments from this PR https://github.com/TexasInstruments/processor-sdk-doc/pull/245
Updates include:
- Updating the confirmation of wakeup events to include the pin that caused the wakeup and the last entered low power mode.
- Increasing readability for setting CPU resume constraints where the resume latency is referenced in ms and not us

Additional LPM documentation updates

---

CONTRIBUTING.md

I've seen a lot of confusion around this lately, and there are still a lot of examples of bad ifconfig usage in the documentation. Add a section to try and clarify ifconfig behavior.

docs(contributing): add section for ifconfig behavior

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/CPSW-CBS.rst

CPSW driver has enabled p0-rx-ptype-rrobin flag in default configuration. To verify CBS feature, p0-rx-ptype-rrobin flag should be turned off, update the documentation to reflect the same changes.

docs(linux): Network: CPSW-CBS: Update CPSW TSN-CBS Documentation

---

source/buildroot/Building_Buildroot_Image.rst

Updated the building the buildroot image instructions with the latest relase tag for am62x platform.

fix(buildroot): Update the build instructions with latest relase tag.

---

source/devices/J7_Family/linux/_Release_Specific_Kernel_Performance_Guide.rst

Add missing performance data for MMC_RAW_FIO_1G for j742s2_evm-fs

perf(linux): Add performance data for j742s2

---

.github/workflows/deploy.yml

Find operates in breadth-first by default. There can only be one index per directory. Might as well shorten this find expression to print and bail out after the first match.
Also resolves the issue where other non-root index files will be picked as the root index due to sorting precedence.

ci(previews): fix index identifier function

---

source/linux/Foundational_Components_ATF.rst

TARGET_BOARD is always "lite" and not "generic" when building for J722S. Remove the wrong build instruction that also gets built.
Reported-by: Keerthy <j-keerthy@ti.com>
Signed-off-by: Neha Malcom Francis <n-francis@ti.com>

fix(TFA): Fix build instruction for J722S

---

source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet.rst

Current documentation doesn't explicitly talk about the limitations in single EMAC support for a given MII configuration. Document the steps which are supposed to be followed by the customers for RGMII and MII.

fix(PRU-ICSS): Fix MII support documentation for single EMAC

---

source/devices/AM57X/linux/Release_Specific_Release_Notes.rst
source/devices/AM62LX/linux/Release_Specific.rst
source/devices/AM62PX/linux/Release_Specific.rst
source/devices/AM62X/linux/Release_Specific.rst
source/devices/AM64X/linux/Release_Specific.rst
source/linux/Foundational_Components/_OpenCV.rst
source/linux/Release_Specific_PLSDK_Release_Notes.rst

Fix links to Release_Specific_Release_Notes in common documentation and make sure it's actually included in the toc tree for all platforms. This disconnect from toc tree and toc.txt files is part of the motivation for the proposed index file structure.

chore(platforms-and-version): fix linking and toc tree

---

source/linux/Overview/GCC_ToolChain.rst
source/linux/Overview/_Processor_SDK_Linux_Directory_Structure.rst

AM62LX SDK folder doesn't have k3-r5-devkit folder. Exclude it.

fix(directory-structure): Update the directory for AM62LX

---

README.md

Moves git clone section above install tools. Updates two
install tool versions that were broken.
Signed-off-by: Jonas Wood <jw@ti.com>

docs(README): Updates README commands

---

source/linux/Foundational_Components/U-Boot/UG-DFU.rst
source/linux/Foundational_Components/U-Boot/UG-General-Info.rst

To enable USB DFU boot on J722S SoC, the bootloader "tiboot3.bin" has to be built by applying the config fragment "am62x_r5_usbdfu.config" on "j722s_evm_r5_defconfig".
To enable USB MSC boot on J722S SoC, the bootloader "tiboot3.bin" has to be built by applying the config fragment "am62x_r5_usbmsc.config" on "j722s_evm_r5_defconfig".
Document this.
While at it, update the format in the existing table that documents the configs to be used for various boot-modes, by switching to the newer notation for representing files.

feat(U-Boot): J722S: Update config fragments for DFU and MSC boot

---

configs/AM64X/AM64X_linux_toc.txt
source/linux/Foundational_Components/U-Boot/UG-RemoteProc.rst

Document update for AM64 early boot support.

AM64 Early boot support

---

.gitignore
.vale.ini

Red Hat has a pretty good template for this thing [1] and it already understands RST. Might as well pick it up here. Fair warning, it's much more picky than I am. I'm not entirely sure if we should add it to the PR checker right now, as even my stuff was flagged to hell and back.
[1] https://github.com/redhat-documentation/vale-at-red-hat
May be good enough to address #19 in the future though.

chore: add vale config for prose and spell checking

---

source/devices/AM62X/linux/Release_Specific_Release_Notes.rst

EXT_EP-12076: "copying files to eMMC triggers cqe error" Is not a SW Bug on 11.00 Release.
The correct bug was https://sir.ext.ti.com/jira/browse/EXT_EP-12086 and Is fixed in 10.01 release already.
This fix is to cleanup Release notes reference to reflect right SDK status.

docs(linux): AM62X: Issue_Tracker: Remove eMMC bug ref: EXT_EP-12076

---

configs/AM67A/AM67A_linux_config.txt
configs/J7200/J7200_linux_config.txt
configs/J722S/J722S_linux_config.txt

This is wrong for some platforms, update them to fix the builds.

fix(OP-TEE): configs: Fix OPTEE_TARGET_FLAVOUR

---

source/linux/Foundational_Components/U-Boot/UG-General-Info.rst

Caught a small typo while reading U-Boot docs. This corrects it.

fix(U-Boot): Correct typo in AM62LX Boot Flow

---

source/common/PRU-ICSS/Overview.rst

The common/PRU-ICSS/Overview section describes am62 SoCs support PRU-SS, but failed to mention that automotive variants do not support this module, so add a warning for this and mention AM62 LP SK does not support PRU-SS.

fix: PRU: Add warning for am62 variants not supporting PRU-SS

---

source/devices/AM62LX/linux/Release_Specific_Release_Notes.rst

Add link for TIFS release notes for version used in SDK 11.0.

docs(linux): AM62LX: Add TIFS firmware release note info

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/PCIe/PCIe_Root_Complex.rst

The Cadence PCIe Controller supports 64-Bit Address Space on the following K3 SoCs:
AM64, AM68, AM69, J7200, J721E, J721S2, J722S, J742S2 and J784S4.
The 64-Bit Address Space provides a larger 4 GB region compared to the 128 MB region in the 32-Bit Address Space. Since the Linux device-tree for the aforementioned SoCs has been updated to switch to the 64-Bit Address Space, document it.

feat(linux): PCIe Root Complex: Document support for 64-Bit Address Space

---

source/devices/AM62LX/linux/Release_Specific_Release_Notes.rst

Guide for Programming user OTP fuses and reduced boot-mode is unique for AM62L.
Adding the label reference in Release summary.

docs(linux): AM62LX: Update Release Summary with OTP Programming label

---

.github/styles/config/vocabularies/PSDK/accept.txt
configs/AM62LX/AM62LX_debian_toc.txt
source/debian/Overview.rst
source/devices/AM62LX/debian/Building_Debian_Image.rst
source/devices/AM62LX/debian/Getting_Started_Guide.rst
source/devices/AM62LX/debian/index.rst

Up until now, Debian images have been built using `ti-bdebstrap`. The docs presently reflect this.
Starting with the 11.00.15.05 Linux SDK release, Debian images are built with the Armbian Build Framework.
Therefore, edit AM62L-specific docs to remove references to `ti-bdebstrap` and add information about Armbian.
Note: Only AM62L-specific changes have been made, using ifconfig's and a new `Building_Debian_Image` file. This is because the other devices are still going to use Debian until the 11.1 release.

feat(debian): AM62LX: Armbian-ize Debian docs for AM62L

---

configs/AM67/AM67_linux_toc.txt
configs/AM67A/AM67A_linux_toc.txt
configs/AM68/AM68_linux_toc.txt
configs/AM68A/AM68A_linux_toc.txt
configs/AM69/AM69_linux_toc.txt
configs/AM69A/AM69A_linux_toc.txt
configs/J7200/J7200_linux_toc.txt
configs/J721E/J721E_linux_toc.txt
configs/J721S2/J721S2_linux_toc.txt
configs/J722S/J722S_linux_toc.txt
configs/J742S2/J742S2_linux_toc.txt
configs/J784S4/J784S4_linux_toc.txt
configs/TDA4VM/TDA4VM_linux_toc.txt

Part of a previous series was flattening some useless includes. This would have been fine on it's own but it was combined with a rename that resulted in invalid toctree entries.
I need to add some scripts to check for this automatically in the future.
Fixes: 65fe58d4 (chore(j7-perf): flatten useless include, 2025-04-30)

fix(j7-perf): update associated toctree entries

---

configs/AM62LX/AM62LX_debian_toc.txt
source/debian/Demo_User_Guides/index_Demos.rst
source/devices/AM62LX/debian/Getting_Started_Guide.rst
source/linux/Demo_User_Guides/TI_LVGL_Demo_User_Guide.rst

Presently, the LVGL OOB page is written under the assumption that the user is using Yocto. For Debian, some of the lines have to be changed. Therefore make those changes.
Also add the doc in Debian's tree.

feat: Add Debian-specific information to LVGL OOB docs

---

.github/workflows/check-files.yml
.github/workflows/comment.yml

Use the delta script to check for any new unreachable collateral files. This will indicate when files not directly part of the documentation should be cleaned up.

ci(check-files): check for unreachable files

---

source/devices/AM62AX/edgeai/getting_started.rst
source/devices/AM62AX/edgeai/pi_hdr_programming.rst

commit 09fca62902ac40074a3cbbc18906593ede9f984e
Author: Chirag Shilwant <c-shilwant@ti.com>
Date:   Mon Jun 30 18:53:19 2025 +0530
fix(edgeai): Switch to code-block & perform miscellaneous fixes
Switch to .. code-block:: text for highlighting name_overlays.
While at it, also perform some minor miscellaneous cleanups.
Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>
<hr>
commit 59e0c7a895958a4fd3ef0f840bb0b95cb478e280
Author: Chirag Shilwant <c-shilwant@ti.com>
Date:   Mon Jun 30 17:34:31 2025 +0530
fix: Switch to role-file
Switch to role :file: [0] for all references of files or directory
[0]: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-file
Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>

edgeai: Minor sphinx fixes

---

source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet.rst

The ICSSG driver reads the firmware names from device tree. Add documentation on how these name are read.

feat(PRU-ICSS): Add firmware name handling

---

source/edgeai/configuration_file.rst
source/edgeai/edgeai_dataflows.rst

In EdgeAI docs, update all applicable sections to recommend ONR-SS-8690-fpnlite-aspp-regnetx400mf-ade20k32-384x384 as default Semantic Segmentation model as ONR-SS-8610-deeplabv3lite-mobv2-ade20k32-512x512 is known to cause frame-buffer starvation on AM62A.

fix(edgeai): Update Default Model for Semantic Segmentation

---

configs/AM62AX/AM62AX_linux_toc.txt
configs/AM62PX/AM62PX_linux_toc.txt
configs/AM62X/AM62X_linux_toc.txt
source/linux/Foundational_Components/U-Boot/UG-Falcon-Mode.rst
source/linux/Foundational_Components/U-Boot/Users-Guide.rst

Falcon mode in U-Boot allows bypassing A53 SPL and U-Boot stage on K3 platforms.
This PR documents the newly added `ti-falcon` override in [meta-ti](https://git.ti.com/cgit/arago-project/meta-ti/commit/?h=master-next&id=7ffd64a5ca2a047ca168797c1214b70f6a75e2da) that enables falcon mode for supported devices (AM62ax, 62p and 62x).

docs(linux): AM62AX, 62PX, 62X: add u-boot falcon mode

---

source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet.rst
source/linux/Foundational_Components/PRU-ICSS/Linux_Drivers/PRU_ICSSG_Ethernet_Switch.rst

This patch updates the PRU_ICSSG_Ethernet.rst and
PRU_ICSSG_Ethernet_Switch.rst documentation files to improve Sphinx compatibility and readability. The following changes are made:
- Replaces all occurrences of "::" used for literal/code blocks with ".. code-block:: console" and ensures proper indentation for code examples and command-line snippets.
- Updates all code and command output blocks to use the correct Sphinx directive, which enables syntax highlighting and consistent formatting in generated documentation.
- Fixes minor typos in comments and documentation text, such as correcting "Fore more details" to "For more details" and improving clarity.
- Ensures consistent formatting of code blocks, command outputs, and configuration examples throughout the documentation.
- No functional …

fix(PRU-ICSS): Convert literal blocks to code-blocks

---

docker/Dockerfile

Add GNU tar for our workflows since BusyBox tar doesn't support advanced command line parameters like hard-dereference.
Dependency for another feature.

feat(docker): add gnu tar for workflows

---

source/devices/AM62X/linux/Release_Specific_Release_Notes.rst

The release 11.1 adds support for AM62SIP in a fashion that customers can take as an example for any 512MiB use case. Therefore add it to the change log.

docs(linux): AM62X: add release note for AM62SIP support

---

.vale.ini

This check is rudimentary and incorrectly tags RST titles as merge conflict notes. As such it should be disabled until it's made aware of RST syntax.
Made in wake of reviewing #359 locally

chore(vale): disable red hat's merge conflict check

---

configs/AM62DX/AM62DX_linux_toc.txt
configs/AM62PX/AM62PX_linux_toc.txt
configs/AM62X/AM62X_linux_toc.txt
configs/AM64X/AM64X_linux_config.txt
configs/AM64X/AM64X_linux_toc.txt
source/devices/AM62DX/linux/Release_Specific.rst
source/devices/AM62DX/linux/Release_Specific_Build_Sheet.rst
source/devices/AM62PX/linux/Release_Specific.rst
source/devices/AM62PX/linux/Release_Specific_Build_Sheet.rst
source/devices/AM62X/linux/Release_Specific.rst
source/devices/AM62X/linux/Release_Specific_Build_Sheet.rst
source/devices/AM64X/linux/Release_Specific.rst
source/devices/AM64X/linux/Release_Specific_Build_Sheet.rst

This adds the support for device specific build sheet information for the devices AM62X, AM62PX, AM64X and AM62DX in github documentation.

feat: Add Software Buildsheets in processor-sdk-doc

---

source/devices/AM62AX/edgeai/faq.rst

* From SDK 11.1, the EdgeAI memory carveouts are maintained as a separate overlay - k3-am62a7-sk-edgeai.dtbo
Hence, add an FAQ for users on the same
* While at it, also fix the faq.rst to follow guidelines for section headers as per [0]
[0]: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections

feat(edgeai): Add a guide on EdgeAI memory carveout overlay

---

source/linux/Foundational_Components/Graphics/Common/Display.rst
source/linux/Foundational_Components/Kernel/Kernel_Drivers/Display/DSS7.rst

The regular kmstest was provided by libdrm and also kmsxx[0], and hence there is a conflict due to whict kmstest is renamed to kmsxxtest in meta-oe[1]. Replace kmstest with kmsxxtest.
Links:
[0]: https://github.com/tomba/kmsxx/
[1]: https://git.openembedded.org/meta-openembedded/tree/meta-oe/dynamic-layers/meta-python/recipes-multimedia/kmsxx/kmsxx_git.bb#n29

docs(linux): Replace kmstest with kmsxxtest

---

source/linux/Demo_User_Guides/AM62D_Dsp_Offload_User_Guide.rst

Update MCU+ SDK 11.1 C7 build instruction reference in AM62D dsp offload demo user guide

fix(linux): update references to point to MCU+ SDK 11.1

---

source/linux/Demo_User_Guides/Edge_AI_Gallery_User_Guide.rst
source/linux/Demo_User_Guides/TI_Apps_Launcher_User_Guide.rst

meta-arago-toolchain lacks Qt6 support for compiling TI Apps Launcher. The correct way to compile it is to use Yocto.
However, for quicker way to compile it, we can also use ARM64 Docker containers. Provide a guide on how to compile ti-apps-launcher using ARM64 Docker container which TI provides [0].
[0] https://github.com/TexasInstruments/ti-docker-images/pkgs/container/debian-arm64

feat: linux: Add compilation instructions for TI Apps Launcher

---

source/debian/_Debian_Developers_Guide.rst
source/devices/AM62LX/debian/index.rst
source/devices/AM62PX/debian/index.rst
source/devices/AM62X/debian/index.rst
source/devices/AM64X/debian/index.rst

In "Welcome to Debian Developer's Guide" section, we are asking people to let us know if they have any ideas by clicking on a hyperlink. The hyperlink leads people to the "Feedback" section, which is the next section on the same page. Unless one is eyeing the address bar on their browser, this gives the effect that the link led nowhere.
Since "Feedback" is the next section, where we ask for ideas anyway, the whole "Please let us know if you have ideas" line is redundant.
So fix this by removing the redundant line.

fix: debian: Remove redundant feedback text

---

source/linux/Foundational_Components/Graphics/Common/Weston.rst

Explain the WAYLAND_DISPLAY variable more since I've gotten questions about it's usage recently. Call out XDG_RUNTIME_DIR as well, to avoid issues.

feat(weston): explain the wayland_display variable

---

source/linux/Foundational_Components/IPC/_RPMsg_char_driver.rst

Update RPMessage ping sample to use default remote endpoint Id: 14. The AM62A firmwares are updated to use these endpoint Ids.

fix(linux): Update rpmsg ping sample for 11.1 release

---

source/devices/AM62AX/linux/Release_Specific_Yocto_layer_Configuration.rst
source/linux/Overview/_Processor_SDK_Building_The_SDK.rst

fix(devices): Update config names for AM62A EdgeAI SDK 11.1
* Fix oe-config names for AM62A EdgeAI SDK 11.1 release.
While at it, also handle miscellaneous cleanups as per
processor-sdk-doc guidelines [0]
[0]: https://github.com/TexasInstruments/processor-sdk-doc/blob/master/CONTRIBUTING.md#indentation-and-whitespace
Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>
<hr>
fix(linux): Update Yocto build steps for AM62A
* Use tabs to showcase both Linux & RT Linux build steps
for EdgeAI filesystem. This was added for other platforms
but was missing for AM62A.
* While at it, also fix the oe-config file name for AM62A
11.1 EdgeAI SDK release.
Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>

fix: Fix oe-config name & yocto build steps

---

source/devices/AM62AX/linux/Release_Specific_Release_Notes.rst
source/linux/Overview/_Processor_SDK_Building_The_SDK.rst

feat(devices): Update What's New section in AM62A Release Notes
* Update "What's New" section in AM62A Release Notes for EdgeAI SDK 11.1.
While at it, also update the release month and handle few fixes & cleanups
Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>
<hr>
fix(linux): Drop tisdk-core-bundle target from AM62A
* Similar to other AM6x, Drop tisdk-core-bundle target
from AM62A as well since it doesn't corresponds to a Full SDK
which is released on ti.com [0]
* While at it, also update the description for tisdk-default-image
[0]: https://www.ti.com/tool/download/PROCESSOR-SDK-LINUX-AM62A/10.01.00.05

AM62A: Updates in Release Notes & Fixes for SDK 11.1

---

source/devices/AM62PX/index_RTOS.rst
source/devices/AM62X/index_RTOS.rst
source/devices/AM64X/index_RTOS.rst
source/devices/AM64X/linux/Overview/Build_and_Run_the_Demos.rst
source/linux/Foundational_Components/Sysfw.rst

Most of the links are updated with the latest string.
Trying to maintain the index.html with version controlled  to identify a specific release documentation.
* AM62, AM62P and AM64 are updated.
* SysFW old link is now pointed to the updated SDK release version 11.01.02. @kavitha-malarvizhi, please verify the same.
* INDUSTRIAL COMM SDK is updated to the latest ECAT reference.
* MOTOR CONTROL for AM64 is obsolete so removed.

fix(linux): Updated 11.01 MCU+SDK Docs URLs for released devices

---

source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/_K3-CPSW-common.rst

Update "ethtool --register-dump|d" output format as per the current ethtool implementation for CPSW driver. Ethtool utility change is present only for Jacinto devices, hence documentation is not changed for Sitara devices.

fix(_K3-CPSW-common): Update ethtool register-dump documentation

---

source/devices/AM62AX/index.rst
source/linux/Documentation_Tarball.rst

* Correct and update the Documentation Tarball Guide, and include it in the AM62A index file.

fix(linux): Update Documentation Tarball Guide & include it in AM62A

---

source/linux/Foundational_Components_Multimedia_wave5.rst

There have been a few cases where pipelines fail to negotiate despite the resolutions and pixel formats being compatible with Wave5 requirements. The negotiation comes from gstreamer plugin not supporting the colorimetry the video was encoded with. Add the list of supported colorimetries the gstreamer V4L2 plugin can work with.

fix(linux): Add Supported Colorimetries to Wave5

---

source/devices/AM62AX/edgeai/faq.rst
source/edgeai/sdk_components.rst

* Bump up to 11.01.07.05 release for all external links to AM62A Linux SDK documentation

fix(edgeai): Update external links to 11.01.07.05

---

.github/styles/config/vocabularies/PSDK/accept.txt
source/linux/Foundational_Components/Kernel/Kernel_Drivers/Storage/MMC-SD.rst
source/linux/Foundational_Components/U-Boot/UG-Memory-K3.rst
source/linux/How_to_Guides/Target/How_to_emmc_boot.rst
source/linux/How_to_Guides/Target/How_to_mmcsd_boot_emmc_uda.rst

This fixes broken links in MMC docs and documents important information on MMC support

fix(linux): Fix broken link to MMC u-boot docs

---

SECURITY.md

* Add SECURITY guide which defines how users should report security vulnerabilities for this repository via TI PSIRT [0]
[0]: https://www.ti.com/support-quality/quality-policies-procedures/report-product-security-vulnerabilities.html

docs(feat): Add SECURITY guide

---

CONTRIBUTING.md

Add examples for the most common commit tags that are used in this repository.

docs(CONTRIBUTING): add examples for common tags

---

configs/AM62AX/AM62AX_linux_toc.txt
configs/AM62LX/AM62LX_linux_toc.txt
configs/AM62PX/AM62PX_linux_toc.txt
configs/AM62X/AM62X_linux_toc.txt
configs/J7200/J7200_linux_toc.txt
configs/J721E/J721E_linux_toc.txt
configs/J721S2/J721S2_linux_toc.txt
configs/J722S/J722S_linux_toc.txt
configs/J742S2/J742S2_linux_toc.txt
configs/J784S4/J784S4_linux_toc.txt
source/linux/Foundational_Components/U-Boot/UG-UMS.rst
source/linux/Foundational_Components/U-Boot/Users-Guide.rst

Add the documentation for UMS(USB Mass Storage) command.

feat(linux): Add the documentation for UMS command
