TexasInstruments/processor-sdk-doc

- .github/workflows/rstcheck.yml
- bin/check-warn.sh
- bin/delta.sh
This is a custom script that checks for any additional rstcheck warnings / errors added for the opened PR. If there is any new warnings / errors it will mark the execution as a failure and comment the findings on the PR.
> Add the first PR checker

- python-scripts/conf.py
- requirements.txt
Add sphinx-copybutton, a small sphinx extension to add a "copy" button to code blocks.
Fixes https://github.com/TexasInstruments/processor-sdk-doc/issues/25
> style(conf): enable sphinx-copybutton

- source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst
Added CSI2RX testing details specifying various combinations of sensors tested across various boards.
Signed-off-by: Yemike Abhilash Chandra <y-abhilashchandra@ti.com>
> fix: Updated the CSI2RX SDK documentation

- source/linux/Foundational_Components/U-Boot/UG-QSPI.rst
Add flash specific details in the OSPI/QSPI documentation.
> linux: u-boot: Add OSPI/QSPI NOR/NAND document

- source/linux/Foundational_Components/Kernel/Kernel_Drivers/QSPI.rst
Remove the NOTE for known issue and add some allignment changes.
> linux: qspi: Edit OSPI/QSPI Document

- configs/AM62PX/AM62PX_linux_toc.txt
- configs/AM62X/AM62X_linux_toc.txt
- configs/AM67/AM67_linux_toc.txt
- configs/AM68/AM68_linux_toc.txt
- configs/AM69/AM69_linux_toc.txt
- configs/J721E/J721E_linux_toc.txt
- configs/J721S2/J721S2_linux_toc.txt
- configs/J722S/J722S_linux_toc.txt
- configs/J742S2/J742S2_linux_toc.txt
- configs/J784S4/J784S4_linux_toc.txt
- source/linux/Foundational_Components/Graphics/Rogue/Build_Guide.rst
- source/linux/Foundational_Components/Graphics/Rogue/Overview.rst
- source/linux/Foundational_Components_Graphics.rst
Add a short guide to go over the different pieces of the proprietary and open source stack, what they do, and how to build them.
> feat(graphics): add a rogue build guide

- source/devices/AM62PX/android/Release_Specific_Release_Notes.rst
- source/devices/AM62X/android/Release_Specific_Release_Notes.rst
We received an e2e error for an audio capture bug.
Document the steps that are needed to solve it by providing a patch and links to other patches that need to be applied.
This is for @vishalmti to be applied on the older (SDK 10.0) documentation
> feat(android): Document audio capture bug

- source/devices/J7_Family/linux/_Release_Specific_Kernel_Performance_Guide.rst
Update performance numbers for CPSW for J7 Devices.
> source: devices: J7_family: Update performance numbers for CPSW

- source/debian/Demo_User_Guides/Chromium_Browser.rst
- Typo/Grammar fixes
- Chromium version update
> Debian chromium 10.1 update

- configs/AM335X/AM335X_linux_toc.txt
- configs/AM437X/AM437X_linux_toc.txt
- configs/AM65X/AM65X_linux_toc.txt
- source/devices/AM335X/linux/Release_Specific_Release_Notes.rst
- source/devices/AM437X/linux/Release_Specific_Release_Notes.rst
- source/devices/AM65X/linux/Release_Specific_Migration_Guide.rst
- source/devices/AM65X/linux/Release_Specific_Release_Notes.rst
This PR removes the redundant and unmaintained sections from AM335x/AM437x/AM65x devices
> Documentation cleanup for SITARA legacy devices

- source/devices/AM62PX/linux/Linux_Performance_Guide.rst
- source/devices/AM62X/linux/Linux_Performance_Guide.rst
Update the power measurements for each low power mode for SDK 10.1.
> docs(linux): AM62X, AM62PX: Update LPM power measurements

- source/devices/AM335X/linux/index.rst
- source/devices/AM437X/linux/index.rst
- source/devices/AM57X/linux/index.rst
- source/devices/AM62AX/index.rst
- source/devices/AM62PX/index.rst
- source/devices/AM62X/index.rst
- source/devices/AM64X/index.rst
- source/devices/AM65X/linux/index.rst
- source/devices/DRA821A/linux/index.rst
- source/devices/J7_Family/linux/_Release_Specific_Kernel_Performance_Guide.rst
- source/devices/J7_Family/linux/index.rst
- source/linux/Foundational_Components/Graphics/SGX/SGX_Debug_Info.rst
- source/linux/Foundational_Components/Power_Management/pm_suspend_resume.rst
- source/linux/Overview/Processor_SDK_Linux_Getting_Started_Guide.rst
- source/linux/index.rst
- source/system/Demo_User_Guides/Seva_Store.rst
Switch all E2E URLs from http to https
> fix(source): Switch all E2E URLs to https

- source/devices/AM335X/linux/Release_Specific_Release_Notes.rst
- source/devices/AM437X/linux/Release_Specific_Release_Notes.rst
- source/devices/AM62AX/linux/Release_Specific_Release_Notes.rst
- source/devices/AM62PX/linux/Release_Specific_Release_Notes.rst
- source/devices/AM62X/linux/Release_Specific_Release_Notes.rst
- source/devices/AM64X/linux/Release_Specific_Release_Notes.rst
- source/devices/AM65X/linux/Release_Specific_Release_Notes.rst
Issue Tracker Update containing details of
Bugs Resolved and Bugs Open.
> docs(linux): Update 10.1 Issue Tracker Details

- source/linux/Foundational_Components/U-Boot/UG-General-Info.rst
Added information regarding boot binaries for J722S HS-SE device
> U-Boot: UG-General-Info: Added info of boot binaries for J722S and AM62P HS-SE

- source/linux/Foundational_Components/System_Security/SELinux.rst
This adds documentation on how to integrate preceding information into the Yocto build for production environments
> feat: Add Yocto building info for SELinux

- source/buildroot/Building_Buildroot_Image.rst
- source/buildroot/Building_Buildroot_Packages.rst
- source/buildroot/Overview.rst
- source/devices/AM62LX/buildroot/Getting_Started_Guide.rst
Update build steps for Buildroot for AM62L 11.0 release.
> feat: Update Buildroot doc for AM62L 11.0 release

- configs/AM62LX/AM62LX_linux_config.txt
- source/linux/Overview/_Processor_SDK_Linux_Software_Developers_Guide.rst
Updated the CONFIG_part_variant in the
AM62L_linux_config.txt to AM62LX.
> fix(linux): Update AM62L linux config file

- source/devices/AM62LX/linux/Linux_Performance_Guide.rst
- source/linux/Foundational_Components/Kernel/Kernel_Drivers/QSPI.rst
- source/linux/Foundational_Components/U-Boot/UG-QSPI.rst
Two patches to add OSPI documentation in U-Boot and Linux.
And one patch to add the performance.
> OSPI documentation

- source/linux/Foundational_Components/Kernel/Kernel_Drivers/Display/DSS7.rst
Add support for DSS Nano which is present in AM62LX EVM
Signed-off: Devarsh Thakkar <devarsht@ti.com>
> DSS7: Add support for AM62LX

- source/linux/Foundational_Components/U-Boot/UG-General-Info.rst
> U-Boot: UG-General-Info: Added BL1 support for AM62L

- configs/AM62LX/AM62LX_linux_toc.txt
- source/devices/AM62LX/linux/Release_Specific_Release_Notes.rst
- source/devices/AM62LX/linux/Release_Specific_Workarounds.rst
- source/linux/Foundational_Components/Power_Management/pm_am62lx_low_power_modes.rst
- source/linux/Foundational_Components/Power_Management/pm_overview.rst
- source/linux/Foundational_Components_Power_Management.rst
Add docs for AM62LX LPM
---
Internal preview: http://lcpd911.dhcp.ti.com/sharing/am62l/docs/linux/Foundational_Components_Power_Management.html
> feat(Linux): Add AM62L specific LPM documentation

- source/linux/Foundational_Components/U-Boot/UG-DDRSS-J7.rst
Add section on partial inline ECC, while at it also clean up using the term "inline ECC" instead of just "ECC". Also update the build instructions to the latest one.
> U-Boot: UG-DDRSS-J7: Add section on partial inline ECC and update

- configs/J784S4/J784S4_linux_toc.txt
- source/linux/How_to_Guides/FAQ/How_to_run_BIST_on_a_core.rst
- source/linux/How_to_Guides_Developer_Notes.rst
Add a How-To Guide for triggering BIST on a core from A72 SPL.
> linux: How-to-Guides: Add guide on triggering BIST

- source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst
Add documentation for new features added in SDK 11.0
> Update CSI2RX Documentation

- configs/AM68/AM68_linux_toc.txt
- configs/AM68A/AM68A_linux_toc.txt
- configs/AM69/AM69_linux_toc.txt
- configs/AM69A/AM69A_linux_toc.txt
- configs/J721S2/J721S2_linux_toc.txt
- configs/J784S4/J784S4_linux_toc.txt
- source/linux/Foundational_Components/U-Boot/UG-HSM.rst
- source/linux/Foundational_Components/U-Boot/Users-Guide.rst
Add a How-To Guide for testing and loading HSM M4 core from R5 SPL.
> feat(U-Boot): Add User Guide on loading HSM M4 core

- source/common/PRU-ICSS/PRU-Getting-Started-Labs.rst
- source/devices/AM62PX/linux/Overview/Build_and_Run_the_Demos.rst
- source/devices/AM62PX/linux/Overview/Download_and_Install_the_SDK.rst
- source/devices/AM62X/linux/Overview/Build_and_Run_the_Demos.rst
- source/devices/AM62X/linux/Overview/Download_and_Install_the_SDK.rst
- source/linux/Foundational_Components/Kernel/Kernel_Drivers/E5010_JPEG_Encoder.rst
- source/linux/Foundational_Components/Kernel/Kernel_Drivers/GPIO.rst
- source/linux/Foundational_Components/U-Boot/UG-Splash-Screen.rst
- source/linux/Foundational_Components_IPC62ax.rst
- source/linux/Foundational_Components_IPC62px.rst
- source/linux/Foundational_Components_IPC62x.rst
- source/linux/Foundational_Components_IPC64x.rst
- source/linux/How_to_Guides/Target/How_to_boot_quickly.rst
- source/system/Demo_User_Guides/Benchmark_Demo_User_Guide.rst
- source/system/Demo_User_Guides/Display_Cluster_User_Guide.rst
Made update to various linux associated pages to 11.00 release or latest.
> chore(linux): misc cleanup of release links to latest release

- source/devices/AM62AX/linux/Linux_Performance_Guide.rst
- source/devices/AM62PX/linux/Linux_Performance_Guide.rst
- source/devices/AM62X/linux/Linux_Performance_Guide.rst
Update the power measurements for each low power mode for SDK 11.0 on AM62PX, AM62AX, and AM62X.
> docs(linux): AM62X, AM62AX, AM62PX: Update LPM power measurements

- source/devices/J7_Family/linux/_Release_Specific_Kernel_Performance_Guide.rst
Update OSPI u-boot performance numbers for J7 family of devices
> Update U-Boot OSPI performance

- source/devices/AM62PX/linux/Release_Specific_Release_Notes.rst
- source/devices/AM62X/linux/Release_Specific_Release_Notes.rst
- source/devices/AM64X/linux/Release_Specific_Release_Notes.rst
Update meta-tisdk HEAD commits for AM62x/AM62P/AM64x based on 11.00.09.04 tag
> fix: Update meta-tisdk head commits for 11.00 release

- configs/J722S/J722S_linux_toc.txt
> feat(Config): Add support for Docker Section

- source/devices/J7_Family/linux/Release_Specific_Release_Notes.rst
Update the meta-tisdk commit ID for the 11.00 release for AM6[789] Processor SDK Linux
> feat: Update release notes for AM6[789] Linux 11.00 release

- .github/workflows/vale.yml
Request a JSON formatted file list to prevent any issues with file name conventions. This also fixes the current issue with the multiple file changes resulting in needlessly parsing all files in the repository.
---
https://github.com/TexasInstruments/processor-sdk-doc/actions/runs/15211986107/job/42788135265
> ci(vale): use json formatted file list

- source/devices/AM62LX/linux/Release_Specific_Release_Notes.rst
Update meta-tisdk tag for AM62Lx to 11.00.15.05
> docs(linux): AM62LX: Update 11.00 meta-tisdk tag

- source/devices/AM62LX/linux/Release_Specific_Release_Notes.rst
Issue Tracker Update containing details of
Bugs Resolved and Bugs Open.
> docs(linux): AM62LX: Update 11.00 Issue Tracker

- source/devices/AM62PX/linux/Linux_Performance_Guide.rst
- source/devices/AM62X/linux/Linux_Performance_Guide.rst
Update the power measurements for each low power mode for SDK 11.1.
> perf(linux): AM62X, AM62PX: Update LPM power measurements

- source/devices/AM64X/linux/RT_Linux_Performance_Guide.rst
- Add tables for Switch Mode and HSR Mode forwarding performance
- Include throughput and CPU load data for HW and SW offload scenarios
> feat(ICSSG): Add ICSSG performance data for Switch and HSR modes

- source/devices/AM64X/linux/RT_Linux_Performance_Guide.rst
Update 11.1 performance numbers from ICSSG manual testing
> perf(linux): AM64X: Update 11.1 performace numbers for ICSSG

- source/devices/AM62DX/linux/Release_Specific_Build_Sheet.rst
Update buildsheet for AM62D 11.1 release.
> feat(linux): Update buildsheet for AM62D

- source/devices/AM62AX/linux/Release_Specific_Migration_Guide.rst
- source/devices/AM62AX/linux/Release_Specific_Release_Notes.rst
- source/devices/AM62AX/linux/Release_Specific_Yocto_layer_Configuration.rst
> docs(linux): AM62AX: Update 11.01 Release tag info

- source/devices/AM62AX/linux/Linux_Performance_Guide.rst
- source/devices/AM62PX/linux/Linux_Performance_Guide.rst
- source/devices/AM64X/linux/Linux_Performance_Guide.rst
- source/linux/Foundational_Components/U-Boot/UG-QSPI.rst
1. Add/Update the performance numbers for 11.01 release
2. Add a workaround for OSPI NOR boot failure in AM62P
> OSPI Doc Updates

- source/linux/Foundational_Components/Graphics/Rogue/Overview.rst
Update the note about the external module location for multiple kernel configurations.
> chore(gfx): update external module path
